# Generated by Django 5.1 on 2024-09-10 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='artigo',
            old_name='ultima_atualizacao',
            new_name='modificado_em',
        ),
        migrations.AddField(
            model_name='artigo',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artigo',
            name='sugestoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='artigos/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autores',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='palavras_chave',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='revista',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PermissaoExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissao_exclusao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_antigo', models.CharField(max_length=255)),
                ('resumo_antigo', models.TextField()),
                ('abstract_antigo', models.TextField()),
                ('data_modificacao', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes_relacionadas', to='artigos.artigo')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='revisoes',
            field=models.ManyToManyField(blank=True, related_name='artigos', to='artigos.revisao'),
        ),
    ]
